### ISSUE TITLE
[feat] transparent menu items

### ISSUE THREAD

**Issue by abose** [phcode-dev/phoenix#968]
### Describe the problem

![image](https://user-images.githubusercontent.com/5336369/216755624-9ef74116-8d49-4c98-950d-1c135e8cf620.png)

### Describe the solution you'd like

Sample:
background-color: rgba(255,255,255,0.5);
    backdrop-filter: blur(5px);

**Comment by abose** [comment]
Primary change: https://github.com/phcode-dev/phoenix/blob/main/src/styles/brackets_patterns_override.less#L188
add the following line:
```css
background-color: rgba(255,255,255,0.5);
.dark & {
    background-color: rgba(0,0,0,0.5);
}
backdrop-filter: blur(5px);
```

But we need to take care of the following before merging to core:
1. Submenus and main menus of navbar
2. sub and main menus or editor and all other menus
3. themability and other break validation
